[[redirects]]
  from = "/api/*"
  to = "http://109.73.206.144:6969/api/:splat"
  status = 200
  force = true

# Добавьте явные правила для каждого endpoint
[[redirects]]
  from = "/incomes"
  to = "http://109.73.206.144:6969/api/incomes"
  status = 200
  force = true

[[redirects]]
  from = "/orders"
  to = "http://109.73.206.144:6969/api/orders"
  status = 200
  force = true

[[redirects]]
  from = "/sales"
  to = "http://109.73.206.144:6969/api/sales"
  status = 200
  force = true

[[redirects]]
  from = "/stocks"
  to = "http://109.73.206.144:6969/api/stocks"
  status = 200
  force = true